### ISSUE TITLE
Warning SDK

### ISSUE THREAD

**Issue by ifraer** [devinotelecom/push-ios-demo#2]
I downloaded the demo version. I tried to start it and immediately gives a warning:
<import DevinoSDK> - Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler: /push-ios-demo-master/DevinoSDK.framework/Modules/DevinoSDK.swiftmodule/arm64-apple-ios.swiftmodule
Tell me what to do?

**Comment by abudanov** [comment]
@ifraer you should compile the module from the [iOS SDK sources](https://github.com/devinotelecom/push-ios-sdk) with the necessary version of Swift.
